#!/usr/bin/env zsh

# Common zprofile for all systems
source "${HOME}/.zsh/common/zprofile"

typeset -gU path fpath

path=(
    $path
    ${HOME}/.local/bin/perso(N-/)
)

fpath=(
    $fpath
    ${HOME}/.local/bin/perso(N-/)
)