#!/usr/bin/env zsh

typeset -gU path fpath

path=(
    $path
    /usr/local/{,s}bin(N-/)
    /snap/bin(N-/)
    ${HOME}/.local/bin(N-/)
    ${HOME}/.local/bin/common(N-/)
)

fpath=(
    $fpath
    ${HOME}/.local/bin/common(N-/)
)

bindkey '^[[1;5D' backward-word
bindkey '^[[1;5C' forward-word